services:
  mariadb:
    image: mariadb:10.11
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql:Z
      - ./dumps:/home/dumps

    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:6.6.1-php8.3-fpm
    user: "1000"
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./wp:/var/www/html

  nginx:
    image: nginx:latest
    restart: always
#    user: "1000"
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wp:/var/www/html
